### ISSUE TITLE
Works in my machine too

### ISSUE THREAD

**Issue by mh4x0f** [pablonoya/awesomewm-configuration#3]
I port your control-center and notification-center for my config,  thanks for share this implementation. 

![2023-10-03_11-22](https://github.com/pablonoya/awesomewm-configuration/assets/6795613/92629b41-d278-4e27-a0fb-be080e3d7ea0)
![2023-10-02_00-16](https://github.com/pablonoya/awesomewm-configuration/assets/6795613/49598447-c120-4eff-b296-f7a0b0f91907)

**Comment by pablonoya** [comment]
Looks great!, glad to have contributed to your config
